### ISSUE TITLE
The latest version seems to conflict with the mods in my mod pack, but the older version doesn't have this problem

### ISSUE THREAD

**Issue by 19300000** [KatatsumuriPan/Nutrition-Unofficial-Extended-Life#5]
[crash-reports.zip](https://github.com/user-attachments/files/17960741/crash-reports.zip)

**Comment by KatatsumuriPan** [comment]
Please give me the reports as .txt, not .zip.
(Windows Defender blocks it.)

**Comment by 19300000** [comment]
[crash-2024-11-29_22.47.48-client.txt](https://github.com/user-attachments/files/17972896/crash-2024-11-29_22.47.48-client.txt)
[latest.log](https://github.com/user-attachments/files/17972897/latest.log)
[Output before the game crashes.txt](https://github.com/user-attachments/files/17972898/Output.before.the.game.crashes.txt)

**Comment by KatatsumuriPan** [comment]
OK, I'll fix it.

**Comment by KatatsumuriPan** [comment]
Now fixed! https://github.com/KatatsumuriPan/Nutrition-Unofficial-Extended-Life/pull/6
